### ISSUE TITLE
install correct libraries and let fleur use them

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/ansible-role-fleur#2]
We currently install these packages:
https://github.com/marvel-nccr/ansible-role-fleur/blob/06ba56f5a84b8a4b5ca8c63f0763211865598ab5/tasks/main.yml#L9-L30

Looking at the [configure output on travis](https://github.com/marvel-nccr/ansible-role-fleur/files/2453340/travis.txt), we should
 - [x] make sure OpenMPI is used to build a parallel version of fleur
 - [ ] make sure libfftw3 is necessary (it seems fleur only cares about MKL fft (?))
 - [x] check whether compilation works with default gcc-7/gfortran-7 compilers

**Comment by ltalirz** [comment]
When enabling MPI, it turns out that some (but not all) tests of the MPI executable fail:
* see [travis](https://travis-ci.org/marvel-nccr/ansible-role-fleur/builds/438093136#L494)
* see [extracted test log](https://github.com/marvel-nccr/ansible-role-fleur/files/2453371/mpi-travis.txt)

Or find the gist of it below:
```
The following tests FAILED:
\t 28 - FLEUR_MPI:CuBulk (Failed)
\t 29 - FLEUR_MPI:CuBulkXML (Failed)
\t 32 - FLEUR_MPI:Fe-Atom (Failed)
\t 37 - FLEUR_MPI:Fe_bct (Failed)
\t 38 - FLEUR_MPI:Fe_bctXML (Failed)
\t 39 - FLEUR_MPI:PTO (Failed)
\t 40 - FLEUR_MPI:PTOXML (Failed)
\t 43 - FLEUR_MPI:PTO-SOC (Failed)
\t 46 - FLEUR_MPI:Fe_bct_SOCXML (Failed)
\t 48 - FLEUR_MPI:SiFilmSlicePlotXML (Failed)
```

Note: this could be an issue of compute/memory limitations on travis. Once we're able to run the tests on QM locally, figure out whether the tests still fail.

**Comment by ltalirz** [comment]
After managing to get the code to run on QM on virtualbox as well (using mpif90 did the trick), it turns out the same tests fail here as well:
```
    The following tests FAILED:
             28 - FLEUR_MPI:CuBulk (Failed)
             29 - FLEUR_MPI:CuBulkXML (Failed)
             32 - FLEUR_MPI:Fe-Atom (Failed)
             37 - FLEUR_MPI:Fe_bct (Failed)
             38 - FLEUR_MPI:Fe_bctXML (Failed)
             39 - FLEUR_MPI:PTO (Failed)
             40 - FLEUR_MPI:PTOXML (Failed)
             43 - FLEUR_MPI:PTO-SOC (Failed)
             46 - FLEUR_MPI:Fe_bct_SOCXML (Failed)
             48 - FLEUR_MPI:SiFilmSlicePlotXML (Failed)
```

For info, here the output of the last test 48 (which failed)
[out.txt](https://github.com/marvel-nccr/ansible-role-fleur/files/2453400/out.txt)

**Comment by ltalirz** [comment]
For latest travis build with MaxR3, see here:
https://travis-ci.org/marvel-nccr/ansible-role-fleur/jobs/438141990

**Comment by broeder-j** [comment]
Comment to the FFT:
Yes, FLEUR only cares about MKL FFT in this version. But it is optional, because otherwise FLEUR uses its internal FFT. In the FLAPW method the FFTs take only a small portion of the runtime (compared to the PW case). Therefore it should be fine without MKL. What causes the MPI tests to fail I can't say from the information given. We will check on the mpif90 compilation of this versions on our machine. 

Do you actually want to run the parallel FLEUR multi node version on Quantum mobile? The serial version has openmp for kpoint parallelization per default, which is enough to use any common small node so far.

**Comment by ltalirz** [comment]
Closing this in favor of #4 

FFT libraries removed in e4eb7c4bf0e564c7016014596371a86a5deb4259
For the moment we continue to build the parallel version (shouldn't hurt).
