### ISSUE TITLE
consider adding standard parameter sets

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/ansible-role-fleur#6]
@broeder-j We're including a couple of pseudopotentials for Quantum Espresso in Quantum Mobile (since they don't ship with the code).
How is it for fleur, are a set of standard PPs already included?
If not, can you point me to a zip that I should download?

**Comment by broeder-j** [comment]
@Italirz FLEUR is an all-electron code, we don't have any pseudo potentials ;-).

But we have default parameters form muffin tin radii and so on, which may be very tricky for non expert users and often a pitfall leading to low quality work. This is why we have an input generator before FLEUR. We are working hard on improving smart defaults to make FLEUR robust in a HTC environment, while at the same time being able to ensure the all-electron accuracy, which is one of the main challenges from our point and of our/my work.

**Comment by ltalirz** [comment]
hehe - oops ;-) I should give it a try once!
Ok, so I understand these default radii etc. are handled by inpgen , so there is no need to include any extra parameters beside the code
