### ISSUE TITLE
Consider installing openBLAS instead, the Fleur executable is really slow.

### ISSUE THREAD

**Issue by broeder-j** [marvel-nccr/ansible-role-fleur#7]
Consider installing  openBLAS instead of the default default-Netlib-BLAS and link it to Fleur.
The default-Netlib-BLAS considerably slows down Fleur.

**Comment by ltalirz** [comment]
@broeder-j thanks for the note, would you be willing to make a PR for  this?

**Comment by ltalirz** [comment]
I notice that this role hasn't been updated in a while and needs a fix for the molecule tests - will do this now

**Comment by broeder-j** [comment]
@ltalirz: I would. Till when do you need this? I would first have to learn a bit how to check that everything works with the role

**Comment by ltalirz** [comment]
sorry, I just realized I closed the wrong issue ;-)

I've changed it to openblas now - did not check that it is actually being used by fleur, however (I guess it must be, since it wouldn't work otherwise?)
