### ISSUE TITLE
Consider using a more modern gfortran compiler instead of gfortran-6

### ISSUE THREAD

**Issue by broeder-j** [marvel-nccr/ansible-role-fleur#9]
this role uses gfortran-6 because the prior ubuntu version did not have newer gfortran compilers in there default repos.
Use gfortran-7, 8 or 9, as long it is in all ubuntu versions this role is to be build on.

@ltalirz: You do not have to do this now, for this release. For the next ones we might text something and contribute here.

**Comment by ltalirz** [comment]
please feel free to update!

**Comment by broeder-j** [comment]
Ok I have checked. the default gfortran for 18.04 is gfortran 7.5, which is fine. The fixed gfortran-6 install is only for the ubuntu 16.04 which is needed. The newest QM is on ubuntu 18.04. Therefore, this is all ok and I close this. If the Fleur developers think a newer gfortran is better we will make a pull request.
